dist: xenial

arch:
  - amd64

os: linux

language: shell

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

before_install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- sudo service docker start
- >
  if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
    echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
  fi
- docker run --rm --privileged multiarch/qemu-user-static:register
- docker --version
- docker buildx create --use

script:
- docker buildx ls; docker ps

deploy:
  - provider: script
    edge: true
    script: docker buildx build --platform linux/arm64 -t kodumbeats/appwriteclitest:0.3 ./ --push
    on:
      repo: kodumbeats/sdk-for-cli
      branch: fix-buildx-qemu
